# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47d9408190c40b59a585b921766656f91e1bfcc106e99938fa36431545d5f8dcca3a234b941138e9ae783c0f6a8710b1af54770912a32c67d13b14705fc4775c

test:
  secret_key_base: b2f172eca9842efd9454d9d105de352ba603e824dc1fd9f0f3f86fb64e9b00dc5eb3fa0d27478d15fec41473c643d2b77d2148b392c8255f9ff33e44deb41d65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
